ALTER SESSION SET CURRENT_SCHEMA = ARYA;

CREATE TABLE apple_account_users (
  user_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name      VARCHAR2(100) NOT NULL,
  last_name       VARCHAR2(100) NOT NULL,
  email           VARCHAR2(255) NOT NULL,
  password_hash   VARCHAR2(255) NOT NULL,
  phone_number    VARCHAR2(30),
  country         VARCHAR2(100) NOT NULL,
  birth_date      DATE NOT NULL,
  created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  status          VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT uq_apple_account_users_email UNIQUE (email),
  CONSTRAINT chk_apple_account_users_status CHECK (status IN ('ACTIVE','LOCKED','DISABLED'))
);

CREATE INDEX idx_apple_account_users_phone ON apple_account_users (phone_number);
