-- V14: Email template system for communications hub
CREATE TABLE EMAIL_TEMPLATES (
    template_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR2(255) NOT NULL,
    description    VARCHAR2(2000),
    category       VARCHAR2(50) NOT NULL,
    subject        VARCHAR2(500) NOT NULL,
    from_name      VARCHAR2(255),
    body_html      CLOB NOT NULL,
    body_json      CLOB,
    merge_fields   CLOB,
    status         VARCHAR2(20) DEFAULT 'DRAFT',
    is_default     NUMBER(1) DEFAULT 0,
    created_by     NUMBER,
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE EMAIL_TEMPLATE_ASSIGNMENTS (
    assignment_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id    NUMBER NOT NULL,
    program_id     NUMBER,
    survey_id      NUMBER,
    trigger_type   VARCHAR2(50) NOT NULL,
    send_delay_days NUMBER DEFAULT 0,
    is_active      NUMBER(1) DEFAULT 1,
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_assignment_template FOREIGN KEY (template_id) REFERENCES EMAIL_TEMPLATES(template_id),
    CONSTRAINT fk_assignment_program FOREIGN KEY (program_id) REFERENCES PROGRAMS(program_id),
    CONSTRAINT fk_assignment_survey FOREIGN KEY (survey_id) REFERENCES SURVEYS(survey_id)
);

CREATE INDEX idx_template_category ON EMAIL_TEMPLATES(category);
CREATE INDEX idx_template_status ON EMAIL_TEMPLATES(status);
CREATE INDEX idx_assignment_template ON EMAIL_TEMPLATE_ASSIGNMENTS(template_id);
CREATE INDEX idx_assignment_program ON EMAIL_TEMPLATE_ASSIGNMENTS(program_id);
CREATE INDEX idx_assignment_survey ON EMAIL_TEMPLATE_ASSIGNMENTS(survey_id);

-- Seed default templates
INSERT INTO EMAIL_TEMPLATES (name, description, category, subject, from_name, body_html, status, is_default) VALUES
('Survey Invitation', 'Default survey invitation email', 'INVITATION', 'You are invited to complete: {{survey_title}}', 'Teammate Voices', '<div style="font-family: -apple-system, BlinkMacSystemFont, sans-serif; max-width: 600px; margin: 0 auto; padding: 32px;"><h1 style="color: #1d1d1f; font-size: 24px;">Hello {{participant_name}},</h1><p style="color: #6e6e73; font-size: 16px; line-height: 1.6;">You have been invited to complete the <strong>{{survey_title}}</strong> survey as part of the <strong>{{program_name}}</strong> program.</p><p style="color: #6e6e73; font-size: 16px; line-height: 1.6;">Your feedback is valuable and helps us improve. This survey is {{#if is_anonymous}}completely anonymous{{/if}}.</p><div style="text-align: center; margin: 32px 0;"><a href="{{survey_link}}" style="display: inline-block; padding: 14px 32px; background: #007aff; color: #fff; text-decoration: none; border-radius: 8px; font-weight: 600; font-size: 16px;">Take Survey</a></div><p style="color: #a1a1a6; font-size: 14px;">If you have questions, please contact your manager {{manager_name}}.</p></div>', 'ACTIVE', 1);

INSERT INTO EMAIL_TEMPLATES (name, description, category, subject, from_name, body_html, status, is_default) VALUES
('Survey Reminder', 'Default survey reminder email', 'REMINDER', 'Reminder: Please complete {{survey_title}}', 'Teammate Voices', '<div style="font-family: -apple-system, BlinkMacSystemFont, sans-serif; max-width: 600px; margin: 0 auto; padding: 32px;"><h1 style="color: #1d1d1f; font-size: 24px;">Hi {{participant_name}},</h1><p style="color: #6e6e73; font-size: 16px; line-height: 1.6;">This is a friendly reminder to complete the <strong>{{survey_title}}</strong> survey. Your input matters!</p><div style="text-align: center; margin: 32px 0;"><a href="{{survey_link}}" style="display: inline-block; padding: 14px 32px; background: #007aff; color: #fff; text-decoration: none; border-radius: 8px; font-weight: 600; font-size: 16px;">Complete Survey</a></div><p style="color: #a1a1a6; font-size: 14px;">Thank you for your time.</p></div>', 'ACTIVE', 1);

INSERT INTO EMAIL_TEMPLATES (name, description, category, subject, from_name, body_html, status, is_default) VALUES
('Thank You', 'Default thank you email after survey completion', 'THANK_YOU', 'Thank you for completing {{survey_title}}', 'Teammate Voices', '<div style="font-family: -apple-system, BlinkMacSystemFont, sans-serif; max-width: 600px; margin: 0 auto; padding: 32px;"><h1 style="color: #1d1d1f; font-size: 24px;">Thank you, {{participant_name}}!</h1><p style="color: #6e6e73; font-size: 16px; line-height: 1.6;">Your response to the <strong>{{survey_title}}</strong> survey has been recorded. We appreciate you taking the time to share your feedback.</p><p style="color: #6e6e73; font-size: 16px; line-height: 1.6;">Your insights help us make meaningful improvements to the {{program_name}} program.</p></div>', 'ACTIVE', 1);
