-- V15: Seed survey-specific email templates

-- Teammate Voices (Intern Program) templates
INSERT INTO EMAIL_TEMPLATES (name, description, category, subject, from_name, body_html, status) VALUES
('Intern Program - Initial Invitation', 'First invitation for intern cohort feedback survey', 'INVITATION',
'Your feedback matters: {{survey_title}}', 'Teammate Voices',
'<div style="font-family:-apple-system,BlinkMacSystemFont,sans-serif;max-width:600px;margin:0 auto;padding:40px 32px;color:#1d1d1f"><div style="text-align:center;margin-bottom:32px"><div style="display:inline-block;background:#012169;color:#fff;font-weight:700;font-size:14px;padding:8px 20px;border-radius:6px;letter-spacing:0.5px">TEAMMATE VOICES</div></div><h1 style="font-size:26px;font-weight:700;margin:0 0 16px">Hello {{participant_name}},</h1><p style="font-size:16px;line-height:1.7;color:#424245;margin:0 0 16px">You have been selected to participate in the <strong>{{survey_title}}</strong> survey as part of the <strong>{{program_name}}</strong> program.</p><p style="font-size:16px;line-height:1.7;color:#424245;margin:0 0 24px">Your honest feedback about the intern cohort experience helps us improve the program for future participants.</p><div style="text-align:center;margin:32px 0"><a href="{{survey_link}}" style="display:inline-block;padding:14px 40px;background:#007aff;color:#fff;text-decoration:none;border-radius:10px;font-weight:600;font-size:16px">Start Survey</a></div><div style="background:#f5f5f7;border-radius:12px;padding:20px;margin:24px 0"><p style="font-size:14px;color:#6e6e73;margin:0"><strong>Survey details:</strong></p><ul style="font-size:14px;color:#6e6e73;margin:8px 0 0;padding-left:20px;line-height:1.8"><li>Estimated time: 10-15 minutes</li><li>6 sections covering your full experience</li><li>Completely anonymous</li><li>Deadline: {{survey_due_date}}</li></ul></div><p style="font-size:14px;color:#86868b;margin:24px 0 0">Questions? Reach out to your manager {{manager_name}}.</p><hr style="border:none;border-top:1px solid #e5e5ea;margin:32px 0"><p style="font-size:12px;color:#a1a1a6;text-align:center">{{company_name}} | Teammate Voices Program</p></div>',
'ACTIVE');

INSERT INTO EMAIL_TEMPLATES (name, description, category, subject, from_name, body_html, status) VALUES
('Intern Program - Reminder', 'Reminder for participants who have not completed the intern survey', 'REMINDER',
'Reminder: Complete your {{survey_title}} feedback', 'Teammate Voices',
'<div style="font-family:-apple-system,BlinkMacSystemFont,sans-serif;max-width:600px;margin:0 auto;padding:40px 32px;color:#1d1d1f"><div style="text-align:center;margin-bottom:32px"><div style="display:inline-block;background:#012169;color:#fff;font-weight:700;font-size:14px;padding:8px 20px;border-radius:6px;letter-spacing:0.5px">TEAMMATE VOICES</div></div><h1 style="font-size:24px;font-weight:700;margin:0 0 16px">Hi {{participant_name}},</h1><p style="font-size:16px;line-height:1.7;color:#424245;margin:0 0 16px">We noticed you have not completed the <strong>{{survey_title}}</strong> survey yet. Your voice matters and we use this feedback to make real improvements.</p><p style="font-size:16px;line-height:1.7;color:#424245;margin:0 0 24px">It only takes about <strong>10-15 minutes</strong> and is completely anonymous.</p><div style="text-align:center;margin:32px 0"><a href="{{survey_link}}" style="display:inline-block;padding:14px 40px;background:#007aff;color:#fff;text-decoration:none;border-radius:10px;font-weight:600;font-size:16px">Complete Survey Now</a></div><p style="font-size:14px;color:#86868b;margin:24px 0 0;text-align:center">Please complete by {{survey_due_date}}. Thank you!</p><hr style="border:none;border-top:1px solid #e5e5ea;margin:32px 0"><p style="font-size:12px;color:#a1a1a6;text-align:center">{{company_name}} | Teammate Voices Program</p></div>',
'ACTIVE');

INSERT INTO EMAIL_TEMPLATES (name, description, category, subject, from_name, body_html, status) VALUES
('Intern Program - Thank You', 'Confirmation after completing the intern program survey', 'THANK_YOU',
'Thank you for completing {{survey_title}}!', 'Teammate Voices',
'<div style="font-family:-apple-system,BlinkMacSystemFont,sans-serif;max-width:600px;margin:0 auto;padding:40px 32px;color:#1d1d1f"><div style="text-align:center;margin-bottom:32px"><div style="display:inline-block;background:#012169;color:#fff;font-weight:700;font-size:14px;padding:8px 20px;border-radius:6px;letter-spacing:0.5px">TEAMMATE VOICES</div></div><div style="text-align:center;margin-bottom:24px"><div style="display:inline-flex;align-items:center;justify-content:center;width:64px;height:64px;background:#dcfce7;border-radius:50%"><span style="font-size:32px">&#10003;</span></div></div><h1 style="font-size:26px;font-weight:700;margin:0 0 16px;text-align:center">Thank you, {{participant_name}}!</h1><p style="font-size:16px;line-height:1.7;color:#424245;margin:0 0 16px;text-align:center">Your response to <strong>{{survey_title}}</strong> has been recorded successfully.</p><p style="font-size:16px;line-height:1.7;color:#424245;margin:0 0 24px;text-align:center">Your feedback is invaluable in helping us improve the {{program_name}} program for future cohorts.</p><hr style="border:none;border-top:1px solid #e5e5ea;margin:32px 0"><p style="font-size:12px;color:#a1a1a6;text-align:center">{{company_name}} | Teammate Voices Program</p></div>',
'ACTIVE');

-- Employee Voice Survey templates
INSERT INTO EMAIL_TEMPLATES (name, description, category, subject, from_name, body_html, status) VALUES
('Employee Voice - Annual Survey Launch', 'Initial invitation for the annual employee engagement survey', 'INVITATION',
'Your voice counts: {{survey_title}} is now open', 'People and Culture',
'<div style="font-family:-apple-system,BlinkMacSystemFont,sans-serif;max-width:600px;margin:0 auto;padding:40px 32px;color:#1d1d1f"><div style="text-align:center;margin-bottom:32px"><div style="display:inline-block;background:#012169;color:#fff;font-weight:700;font-size:14px;padding:8px 20px;border-radius:6px;letter-spacing:0.5px">EMPLOYEE VOICE</div></div><h1 style="font-size:26px;font-weight:700;margin:0 0 16px">Dear {{participant_name}},</h1><p style="font-size:16px;line-height:1.7;color:#424245;margin:0 0 16px">The <strong>{{survey_title}}</strong> is now open! This is your opportunity to share candid feedback about your experience at {{company_name}}.</p><p style="font-size:16px;line-height:1.7;color:#424245;margin:0 0 8px">This year the survey covers:</p><ul style="font-size:15px;color:#424245;line-height:2;padding-left:20px;margin:0 0 24px"><li>Engagement and motivation</li><li>Manager effectiveness</li><li>Growth and career development</li><li>Communication and leadership</li><li>Diversity, equity and inclusion</li><li>Well-being and work-life balance</li><li>Compensation and benefits</li></ul><div style="text-align:center;margin:32px 0"><a href="{{survey_link}}" style="display:inline-block;padding:14px 40px;background:#007aff;color:#fff;text-decoration:none;border-radius:10px;font-weight:600;font-size:16px">Take the Survey</a></div><div style="background:#f0f7ff;border-left:4px solid #007aff;border-radius:0 8px 8px 0;padding:16px 20px;margin:24px 0"><p style="font-size:14px;color:#1d1d1f;margin:0"><strong>Confidentiality:</strong> All responses are completely anonymous. Only aggregated results are shared.</p></div><p style="font-size:14px;color:#86868b;margin:16px 0 0">Estimated time: 15-20 minutes | Deadline: {{survey_due_date}}</p><hr style="border:none;border-top:1px solid #e5e5ea;margin:32px 0"><p style="font-size:12px;color:#a1a1a6;text-align:center">{{company_name}} | People and Culture</p></div>',
'ACTIVE');

INSERT INTO EMAIL_TEMPLATES (name, description, category, subject, from_name, body_html, status) VALUES
('Employee Voice - Final Reminder', 'Urgent final reminder before the annual survey closes', 'REMINDER',
'Last chance: {{survey_title}} closes soon', 'People and Culture',
'<div style="font-family:-apple-system,BlinkMacSystemFont,sans-serif;max-width:600px;margin:0 auto;padding:40px 32px;color:#1d1d1f"><div style="text-align:center;margin-bottom:32px"><div style="display:inline-block;background:#012169;color:#fff;font-weight:700;font-size:14px;padding:8px 20px;border-radius:6px;letter-spacing:0.5px">EMPLOYEE VOICE</div></div><div style="background:#fef9c3;border-radius:10px;padding:16px 20px;text-align:center;margin-bottom:24px"><p style="font-size:15px;color:#854d0e;font-weight:600;margin:0">Survey closes on {{survey_due_date}}</p></div><h1 style="font-size:24px;font-weight:700;margin:0 0 16px">{{participant_name}}, we still need your voice.</h1><p style="font-size:16px;line-height:1.7;color:#424245;margin:0 0 16px">The <strong>{{survey_title}}</strong> is closing soon and we have not received your response yet. Every voice matters and your feedback directly influences the improvements we make.</p><p style="font-size:16px;line-height:1.7;color:#424245;margin:0 0 24px">It takes just <strong>15-20 minutes</strong> and is completely anonymous.</p><div style="text-align:center;margin:32px 0"><a href="{{survey_link}}" style="display:inline-block;padding:14px 40px;background:#ff9500;color:#fff;text-decoration:none;border-radius:10px;font-weight:600;font-size:16px">Complete Before It Closes</a></div><hr style="border:none;border-top:1px solid #e5e5ea;margin:32px 0"><p style="font-size:12px;color:#a1a1a6;text-align:center">{{company_name}} | People and Culture</p></div>',
'ACTIVE');

-- Academy Program templates
INSERT INTO EMAIL_TEMPLATES (name, description, category, subject, from_name, body_html, status) VALUES
('Academy - Program Welcome', 'Welcome email when a participant joins an academy program', 'WELCOME',
'Welcome to {{program_name}}!', 'Learning and Development',
'<div style="font-family:-apple-system,BlinkMacSystemFont,sans-serif;max-width:600px;margin:0 auto;padding:40px 32px;color:#1d1d1f"><div style="text-align:center;margin-bottom:32px"><div style="display:inline-block;background:#5856d6;color:#fff;font-weight:700;font-size:14px;padding:8px 20px;border-radius:6px;letter-spacing:0.5px">ACADEMY</div></div><h1 style="font-size:26px;font-weight:700;margin:0 0 16px;text-align:center">Welcome to {{program_name}}!</h1><p style="font-size:16px;line-height:1.7;color:#424245;margin:0 0 16px">Hi {{participant_name}},</p><p style="font-size:16px;line-height:1.7;color:#424245;margin:0 0 16px">We are excited to have you in the {{program_name}} program! This learning journey is designed to help you grow your skills and advance your career at {{company_name}}.</p><div style="background:#f5f5f7;border-radius:12px;padding:24px;margin:24px 0"><p style="font-size:15px;color:#1d1d1f;font-weight:600;margin:0 0 12px">What to expect:</p><ul style="font-size:14px;color:#6e6e73;margin:0;padding-left:20px;line-height:2"><li>Interactive sessions with expert instructors</li><li>Hands-on workshops and real-world exercises</li><li>Peer learning with your cohort ({{cohort}})</li><li>Post-program feedback survey</li></ul></div><p style="font-size:16px;line-height:1.7;color:#424245;margin:0 0 16px">Your manager {{manager_name}} has been notified and will support you throughout the program.</p><hr style="border:none;border-top:1px solid #e5e5ea;margin:32px 0"><p style="font-size:12px;color:#a1a1a6;text-align:center">{{company_name}} | Learning and Development</p></div>',
'ACTIVE');

INSERT INTO EMAIL_TEMPLATES (name, description, category, subject, from_name, body_html, status) VALUES
('Academy - Post-Training Feedback', 'Survey invitation sent after completing an academy program', 'INVITATION',
'Share your {{program_name}} experience', 'Learning and Development',
'<div style="font-family:-apple-system,BlinkMacSystemFont,sans-serif;max-width:600px;margin:0 auto;padding:40px 32px;color:#1d1d1f"><div style="text-align:center;margin-bottom:32px"><div style="display:inline-block;background:#5856d6;color:#fff;font-weight:700;font-size:14px;padding:8px 20px;border-radius:6px;letter-spacing:0.5px">ACADEMY</div></div><h1 style="font-size:24px;font-weight:700;margin:0 0 16px">Congratulations on completing {{program_name}}, {{participant_name}}!</h1><p style="font-size:16px;line-height:1.7;color:#424245;margin:0 0 16px">We would love to hear about your experience. Your feedback helps us improve the program for future participants.</p><p style="font-size:16px;line-height:1.7;color:#424245;margin:0 0 24px">The <strong>{{survey_title}}</strong> covers course content, instructor quality, practical application, and your overall experience.</p><div style="text-align:center;margin:32px 0"><a href="{{survey_link}}" style="display:inline-block;padding:14px 40px;background:#5856d6;color:#fff;text-decoration:none;border-radius:10px;font-weight:600;font-size:16px">Share Your Feedback</a></div><div style="background:#f5f5f7;border-radius:12px;padding:16px 20px;margin:24px 0"><p style="font-size:14px;color:#6e6e73;margin:0">Estimated time: 10 minutes | 6 sections | Anonymous responses</p></div><hr style="border:none;border-top:1px solid #e5e5ea;margin:32px 0"><p style="font-size:12px;color:#a1a1a6;text-align:center">{{company_name}} | Learning and Development</p></div>',
'ACTIVE');

INSERT INTO EMAIL_TEMPLATES (name, description, category, subject, from_name, body_html, status) VALUES
('Academy - Completion Certificate', 'Congratulations email when a participant completes an academy program', 'COMPLETION',
'Certificate of Completion: {{program_name}}', 'Learning and Development',
'<div style="font-family:-apple-system,BlinkMacSystemFont,sans-serif;max-width:600px;margin:0 auto;padding:40px 32px;color:#1d1d1f"><div style="text-align:center;margin-bottom:32px"><div style="display:inline-block;background:#5856d6;color:#fff;font-weight:700;font-size:14px;padding:8px 20px;border-radius:6px;letter-spacing:0.5px">ACADEMY</div></div><div style="text-align:center;margin-bottom:24px;padding:32px;background:linear-gradient(135deg,#f0f0ff 0%,#e8f0fe 100%);border-radius:16px;border:2px solid #5856d6"><p style="font-size:12px;color:#5856d6;text-transform:uppercase;letter-spacing:2px;margin:0 0 8px;font-weight:700">Certificate of Completion</p><h1 style="font-size:28px;font-weight:700;margin:0 0 8px;color:#1d1d1f">{{participant_name}}</h1><p style="font-size:16px;color:#6e6e73;margin:0 0 4px">has successfully completed</p><p style="font-size:20px;font-weight:700;color:#5856d6;margin:0">{{program_name}}</p></div><p style="font-size:16px;line-height:1.7;color:#424245;margin:24px 0 16px;text-align:center">Congratulations on your achievement! Your dedication to professional growth sets a great example for the entire organization.</p><hr style="border:none;border-top:1px solid #e5e5ea;margin:32px 0"><p style="font-size:12px;color:#a1a1a6;text-align:center">{{company_name}} | Learning and Development</p></div>',
'ACTIVE');
