-- V18: Workflow audit log for tracking state changes and actions
CREATE TABLE WORKFLOW_AUDIT_LOG (
    audit_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type    VARCHAR2(50) NOT NULL,     -- SURVEY, PROGRAM, EMAIL_TEMPLATE
    entity_id      NUMBER NOT NULL,            -- ID of the entity
    action         VARCHAR2(50) NOT NULL,      -- PUBLISH, UNPUBLISH, CLOSE, SEND_EMAIL, ASSIGN_TEMPLATE
    previous_state VARCHAR2(50),               -- e.g., DRAFT
    new_state      VARCHAR2(50),               -- e.g., ACTIVE
    performed_by   VARCHAR2(255),              -- user who performed the action
    details        CLOB,                       -- JSON with additional context
    ip_address     VARCHAR2(45),               -- client IP
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_audit_entity ON WORKFLOW_AUDIT_LOG(entity_type, entity_id);
CREATE INDEX idx_audit_action ON WORKFLOW_AUDIT_LOG(action);
CREATE INDEX idx_audit_created ON WORKFLOW_AUDIT_LOG(created_at);
