-- V2: Core survey tables (surveys, questions, options)
CREATE TABLE SURVEYS (
    survey_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    description CLOB,
    template_type VARCHAR2(50) DEFAULT 'CUSTOM' NOT NULL,
    status VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL,
    participant_type VARCHAR2(30) DEFAULT 'ALL',
    survey_stage VARCHAR2(30) DEFAULT 'ONBOARDING',
    audience_source VARCHAR2(30) DEFAULT 'CSV_UPLOAD',
    auto_send NUMBER(1) DEFAULT 0,
    created_by NUMBER,
    start_date DATE,
    end_date DATE,
    is_anonymous NUMBER(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_survey_status CHECK (status IN ('DRAFT', 'ACTIVE', 'CLOSED', 'ARCHIVED')),
    CONSTRAINT chk_survey_template CHECK (template_type IN ('CUSTOM', 'TEAM_MATE_VOICES', 'ENGAGEMENT', 'NPS')),
    CONSTRAINT chk_survey_participant_type CHECK (participant_type IN ('NEW_HIRE', 'EXISTING_RESOURCE', 'ALL')),
    CONSTRAINT chk_survey_stage CHECK (survey_stage IN ('ONBOARDING', 'MID_TRAINING', 'END_TRAINING')),
    CONSTRAINT chk_survey_audience CHECK (audience_source IN ('AUTO_API', 'CSV_UPLOAD', 'GOOGLE_SHEET')),
    CONSTRAINT fk_survey_created_by FOREIGN KEY (created_by) REFERENCES USERS(user_id)
);

CREATE TABLE SURVEY_QUESTIONS (
    question_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    survey_id NUMBER NOT NULL,
    question_text VARCHAR2(500) NOT NULL,
    question_type VARCHAR2(30) NOT NULL,
    sort_order NUMBER DEFAULT 0,
    is_required NUMBER(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_question_survey FOREIGN KEY (survey_id) REFERENCES SURVEYS(survey_id) ON DELETE CASCADE,
    CONSTRAINT chk_question_type CHECK (question_type IN ('RATING_SCALE', 'MULTIPLE_CHOICE', 'TEXT', 'MATRIX'))
);

CREATE TABLE SURVEY_OPTIONS (
    option_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id NUMBER NOT NULL,
    option_text VARCHAR2(255) NOT NULL,
    option_value NUMBER,
    sort_order NUMBER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_option_question FOREIGN KEY (question_id) REFERENCES SURVEY_QUESTIONS(question_id) ON DELETE CASCADE
);

CREATE INDEX idx_surveys_status ON SURVEYS(status);
CREATE INDEX idx_surveys_template ON SURVEYS(template_type);
CREATE INDEX idx_surveys_participant_type ON SURVEYS(participant_type);
CREATE INDEX idx_surveys_stage ON SURVEYS(survey_stage);
CREATE INDEX idx_questions_survey ON SURVEY_QUESTIONS(survey_id);
CREATE INDEX idx_options_question ON SURVEY_OPTIONS(question_id);
