-- V30: M360 (360-degree feedback) core tables
-- Cycles belong to a Program; each cycle has phases, rater criteria, enrollments, and rater assignments.

CREATE TABLE M360_CYCLES (
    cycle_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id NUMBER NOT NULL,
    survey_id NUMBER,
    name VARCHAR2(255) NOT NULL,
    description VARCHAR2(2000),
    version NUMBER DEFAULT 1,
    start_date DATE,
    status VARCHAR2(20) DEFAULT 'INACTIVE',
    allow_self_selection NUMBER(1) DEFAULT 1,
    allow_manager_selection NUMBER(1) DEFAULT 1,
    allow_hr_selection NUMBER(1) DEFAULT 0,
    overall_min_raters NUMBER,
    overall_max_raters NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_m360_cycle_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT fk_m360_cycle_program FOREIGN KEY (program_id) REFERENCES PROGRAMS(program_id) ON DELETE CASCADE,
    CONSTRAINT fk_m360_cycle_survey FOREIGN KEY (survey_id) REFERENCES SURVEYS(survey_id)
);

CREATE TABLE M360_CYCLE_PHASES (
    phase_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle_id NUMBER NOT NULL,
    phase_type VARCHAR2(30) NOT NULL,
    is_enabled NUMBER(1) DEFAULT 1,
    start_at TIMESTAMP,
    end_at TIMESTAMP,
    timezone VARCHAR2(50) DEFAULT 'America/New_York',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_m360_phase_type CHECK (phase_type IN ('ENROLLMENT', 'PRE_LAUNCH', 'RATER_SELECTION', 'RATER_APPROVAL', 'RATER_FEEDBACK', 'REPORT_DELIVERY', 'POST_SURVEY')),
    CONSTRAINT fk_m360_phase_cycle FOREIGN KEY (cycle_id) REFERENCES M360_CYCLES(cycle_id) ON DELETE CASCADE,
    CONSTRAINT uq_m360_phase_per_cycle UNIQUE (cycle_id, phase_type)
);

CREATE TABLE M360_RATER_CRITERIA (
    criteria_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle_id NUMBER NOT NULL,
    category VARCHAR2(30) NOT NULL,
    min_count NUMBER DEFAULT 0,
    max_count NUMBER,
    auto_load NUMBER(1) DEFAULT 0,
    is_enabled NUMBER(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_m360_criteria_category CHECK (category IN ('SELF', 'MANAGER', 'INDIRECT_MANAGER', 'PEERS', 'DIRECT_REPORTS', 'BUSINESS_PARTNERS')),
    CONSTRAINT fk_m360_criteria_cycle FOREIGN KEY (cycle_id) REFERENCES M360_CYCLES(cycle_id) ON DELETE CASCADE,
    CONSTRAINT uq_m360_criteria_per_cycle UNIQUE (cycle_id, category)
);

-- Communication activities within a phase (Comms template + date/time rows in the Schedule step)
CREATE TABLE M360_PHASE_ACTIVITIES (
    activity_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phase_id NUMBER NOT NULL,
    activity_name VARCHAR2(255) NOT NULL,
    email_template_id NUMBER,
    activity_date DATE,
    activity_time VARCHAR2(20),
    is_enabled NUMBER(1) DEFAULT 1,
    sort_order NUMBER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_m360_activity_phase FOREIGN KEY (phase_id) REFERENCES M360_CYCLE_PHASES(phase_id) ON DELETE CASCADE,
    CONSTRAINT fk_m360_activity_template FOREIGN KEY (email_template_id) REFERENCES EMAIL_TEMPLATES(template_id)
);

CREATE TABLE M360_ENROLLMENTS (
    enrollment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle_id NUMBER NOT NULL,
    participant_id VARCHAR2(100) NOT NULL,
    manager_name VARCHAR2(255),
    manager_email VARCHAR2(255),
    status VARCHAR2(30) DEFAULT 'ENROLLED',
    participant_token VARCHAR2(255),
    manager_token VARCHAR2(255),
    raters_submitted_at TIMESTAMP,
    raters_approved_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_m360_enrollment_status CHECK (status IN ('ENROLLED', 'RATERS_SUBMITTED', 'RATERS_APPROVED', 'FEEDBACK_IN_PROGRESS', 'COMPLETED')),
    CONSTRAINT fk_m360_enrollment_cycle FOREIGN KEY (cycle_id) REFERENCES M360_CYCLES(cycle_id) ON DELETE CASCADE,
    CONSTRAINT fk_m360_enrollment_participant FOREIGN KEY (participant_id) REFERENCES PARTICIPANTS(participant_id) ON DELETE CASCADE,
    CONSTRAINT uq_m360_enrollment_per_cycle UNIQUE (cycle_id, participant_id),
    CONSTRAINT uq_m360_participant_token UNIQUE (participant_token),
    CONSTRAINT uq_m360_manager_token UNIQUE (manager_token)
);

CREATE TABLE M360_RATER_ASSIGNMENTS (
    rater_assignment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id NUMBER NOT NULL,
    rater_participant_id VARCHAR2(100),
    rater_name VARCHAR2(255) NOT NULL,
    rater_email VARCHAR2(255) NOT NULL,
    relationship VARCHAR2(30) NOT NULL,
    added_by VARCHAR2(20) DEFAULT 'SELF',
    status VARCHAR2(30) DEFAULT 'PENDING_APPROVAL',
    rejection_reason VARCHAR2(1000),
    feedback_token VARCHAR2(255),
    invited_at TIMESTAMP,
    feedback_submitted_at TIMESTAMP,
    email_status VARCHAR2(20) DEFAULT 'NOT_SENT',
    email_template_id NUMBER,
    response_id NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_m360_rater_relationship CHECK (relationship IN ('SELF', 'MANAGER', 'INDIRECT_MANAGER', 'PEERS', 'DIRECT_REPORTS', 'BUSINESS_PARTNERS')),
    CONSTRAINT chk_m360_rater_added_by CHECK (added_by IN ('SELF', 'MANAGER', 'HR_PARTNER', 'SYSTEM')),
    CONSTRAINT chk_m360_rater_status CHECK (status IN ('PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'INVITED', 'IN_PROGRESS', 'SUBMITTED', 'EXPIRED')),
    CONSTRAINT chk_m360_rater_email_status CHECK (email_status IN ('NOT_SENT', 'QUEUED', 'SENT', 'FAILED')),
    CONSTRAINT fk_m360_rater_enrollment FOREIGN KEY (enrollment_id) REFERENCES M360_ENROLLMENTS(enrollment_id) ON DELETE CASCADE,
    CONSTRAINT fk_m360_rater_participant FOREIGN KEY (rater_participant_id) REFERENCES PARTICIPANTS(participant_id),
    CONSTRAINT fk_m360_rater_template FOREIGN KEY (email_template_id) REFERENCES EMAIL_TEMPLATES(template_id),
    CONSTRAINT uq_m360_rater_per_enrollment UNIQUE (enrollment_id, rater_email),
    CONSTRAINT uq_m360_feedback_token UNIQUE (feedback_token)
);

CREATE INDEX idx_m360_cycles_program ON M360_CYCLES(program_id);
CREATE INDEX idx_m360_enrollments_cycle ON M360_ENROLLMENTS(cycle_id);
CREATE INDEX idx_m360_raters_enrollment ON M360_RATER_ASSIGNMENTS(enrollment_id);
CREATE INDEX idx_m360_raters_email ON M360_RATER_ASSIGNMENTS(rater_email);
CREATE INDEX idx_m360_raters_status ON M360_RATER_ASSIGNMENTS(status);
CREATE INDEX idx_m360_activities_phase ON M360_PHASE_ACTIVITIES(phase_id);
