-- V3: Survey response and answer tables
CREATE TABLE SURVEY_RESPONSES (
    response_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    survey_id NUMBER NOT NULL,
    respondent_user_id NUMBER,
    submitted_at TIMESTAMP,
    started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_response_survey FOREIGN KEY (survey_id) REFERENCES SURVEYS(survey_id),
    CONSTRAINT fk_response_user FOREIGN KEY (respondent_user_id) REFERENCES USERS(user_id)
);

CREATE TABLE SURVEY_ANSWERS (
    answer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    response_id NUMBER NOT NULL,
    question_id NUMBER NOT NULL,
    answer_text CLOB,
    answer_value NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_answer_response FOREIGN KEY (response_id) REFERENCES SURVEY_RESPONSES(response_id) ON DELETE CASCADE,
    CONSTRAINT fk_answer_question FOREIGN KEY (question_id) REFERENCES SURVEY_QUESTIONS(question_id)
);

CREATE INDEX idx_responses_survey ON SURVEY_RESPONSES(survey_id);
CREATE INDEX idx_responses_user ON SURVEY_RESPONSES(respondent_user_id);
CREATE INDEX idx_answers_response ON SURVEY_ANSWERS(response_id);
CREATE INDEX idx_answers_question ON SURVEY_ANSWERS(question_id);
