-- V4: Lifecycle tables (participants, assignment rules, dispatches)
CREATE TABLE PARTICIPANTS (
    participant_id VARCHAR2(100) PRIMARY KEY,
    full_name VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) NOT NULL,
    participant_type VARCHAR2(30) NOT NULL,
    training_program VARCHAR2(255),
    cohort VARCHAR2(100),
    start_date DATE NOT NULL,
    expected_end_date DATE,
    is_active NUMBER(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_participant_email UNIQUE (email),
    CONSTRAINT chk_participant_type CHECK (participant_type IN ('NEW_HIRE', 'EXISTING_RESOURCE'))
);

CREATE TABLE ASSIGNMENT_RULES (
    rule_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_name VARCHAR2(255) NOT NULL,
    participant_type VARCHAR2(30) NOT NULL,
    survey_stage VARCHAR2(30) NOT NULL,
    survey_id NUMBER NOT NULL,
    send_day_offset NUMBER,
    is_active NUMBER(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_rule_participant_type CHECK (participant_type IN ('NEW_HIRE', 'EXISTING_RESOURCE', 'ALL')),
    CONSTRAINT chk_rule_stage CHECK (survey_stage IN ('ONBOARDING', 'MID_TRAINING', 'END_TRAINING')),
    CONSTRAINT fk_rule_survey FOREIGN KEY (survey_id) REFERENCES SURVEYS(survey_id) ON DELETE CASCADE
);

CREATE TABLE DISPATCHES (
    dispatch_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_id VARCHAR2(100) NOT NULL,
    survey_id NUMBER NOT NULL,
    survey_stage VARCHAR2(30) NOT NULL,
    dispatch_status VARCHAR2(30) DEFAULT 'PENDING',
    sent_at TIMESTAMP,
    opened_at TIMESTAMP,
    submitted_at TIMESTAMP,
    reminder_count NUMBER DEFAULT 0,
    dispatch_token VARCHAR2(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_dispatch_stage CHECK (survey_stage IN ('ONBOARDING', 'MID_TRAINING', 'END_TRAINING')),
    CONSTRAINT chk_dispatch_status CHECK (dispatch_status IN ('PENDING', 'SENT', 'OPENED', 'SUBMITTED', 'FAILED', 'EXPIRED')),
    CONSTRAINT fk_dispatch_participant FOREIGN KEY (participant_id) REFERENCES PARTICIPANTS(participant_id) ON DELETE CASCADE,
    CONSTRAINT fk_dispatch_survey FOREIGN KEY (survey_id) REFERENCES SURVEYS(survey_id) ON DELETE CASCADE,
    CONSTRAINT uq_dispatch_per_stage UNIQUE (participant_id, survey_id, survey_stage)
);

CREATE INDEX idx_rules_active ON ASSIGNMENT_RULES(is_active);
CREATE INDEX idx_dispatch_status ON DISPATCHES(dispatch_status);
CREATE INDEX idx_dispatch_participant ON DISPATCHES(participant_id);
