-- V6: Programs table
CREATE TABLE PROGRAMS (
    program_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    description CLOB,
    template_type VARCHAR2(50) DEFAULT 'CUSTOM',
    status VARCHAR2(20) DEFAULT 'INACTIVE' NOT NULL,
    survey_progress VARCHAR2(30) DEFAULT 'NOT_STARTED' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_program_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT chk_program_progress CHECK (survey_progress IN ('NOT_STARTED', 'IN_PROGRESS', 'COMPLETE'))
);

CREATE INDEX idx_program_status ON PROGRAMS(status);

-- Seed existing mock programs
INSERT INTO PROGRAMS (name, description, template_type, status, survey_progress)
VALUES ('Enterprise 360 2025 - A',
        'Body text lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse ac dolor hendrerit, efficitur dolor sed, malesuada ex. Cras metus ligula, fermentum eget',
        'TEAMMATE_VOICES', 'ACTIVE', 'NOT_STARTED');

INSERT INTO PROGRAMS (name, description, template_type, status, survey_progress)
VALUES ('Enterprise 360 2025 - B',
        'Body text lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse ac dolor hendrerit, efficitur dolor sed, malesuada ex. Cras metus ligula, fermentum eget',
        'TEAMMATE_VOICES', 'ACTIVE', 'IN_PROGRESS');
